runtime: python311

# Entrypoint corrigido
entrypoint: gunicorn -b :$PORT main:app

# Variáveis de ambiente
env_variables:
  FLASK_APP: main.py
  FLASK_ENV: production
  FLASK_DEBUG: "False"
  
  # Configurações de email (Brevo)
  BREVO_API_KEY: "CHANGE_ME"
  BREVO_SENDER_EMAIL: "srshare2inspire@gmail.com"
  BREVO_SENDER_NAME: "Share2Inspire"
  
  # Configurações Ifthenpay
  IFTHENPAY_GATEWAY_KEY: "CHANGE_ME"
  IFTHENPAY_CALLBACK_KEY: "CHANGE_ME"
  IFTHENPAY_MBWAY_KEY: "CHANGE_ME"
  IFTHENPAY_PAYSHOP_KEY: "CHANGE_ME"
  IFTHENPAY_MULTIBANCO_KEY: "CHANGE_ME"
  
  # Chave secreta Flask
  FLASK_SECRET_KEY: "CHANGE_ME"

# Handlers simplificados
handlers:
- url: /.*
  script: auto
  secure: always

# Configurações de escalabilidade
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.6

# Configurações de recursos
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

