runtime: python311
entrypoint: gunicorn -b :$PORT --workers 1 --threads 8 --timeout 0 main:app

# Variáveis de ambiente não sensíveis
env_variables:
  FLASK_ENV: "production"
  FLASK_DEBUG: "False"
  BREVO_SENDER_EMAIL: "srshare2inspire@gmail.com"
  BREVO_SENDER_NAME: "Share2Inspire"
  IFTHENPAY_MULTIBANCO_ENTITY: "11111"
  IFTHENPAY_MULTIBANCO_SUBENTITY: "999"
  IFTHENPAY_CALLBACK_URL: "https://share2inspire-beckend.lm.r.appspot.com/api/payment/callback"

# Para variáveis sensíveis, use o Secret Manager:
# gcloud secrets create BREVO_API_KEY --data-file=/path/to/brevo_key.txt
# gcloud secrets create IFTHENPAY_API_KEY --data-file=/path/to/ifthenpay_key.txt
# etc.

handlers:
# Configuração específica para API com cabeçalhos CORS
- url: /api/.*
  script: auto
  secure: always
  http_headers:
    Access-Control-Allow-Origin: https://share2inspire.pt
    Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
    Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With
    Access-Control-Allow-Credentials: 'true'

# Configuração para todas as outras rotas
- url: /.*
  script: auto
  secure: always # Força HTTPS
