runtime: python311
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  FLASK_APP: main.py
  FLASK_ENV: production
  FLASK_DEBUG: "False"

handlers:
- url: /api/.*
  script: auto
  secure: always
  http_headers:
    Access-Control-Allow-Origin: https://share2inspire.pt
    Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
    Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With
    Access-Control-Allow-Credentials: 'true'

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: 100ms
  max_concurrent_requests: 50
