runtime: python311

# Entrypoint corrigido
entrypoint: gunicorn -b :$PORT main:app

# Variáveis de ambiente
env_variables:
  FLASK_APP: main.py
  FLASK_ENV: production
  FLASK_DEBUG: "False"
  
  # Configurações de email (Brevo)
  BREVO_API_KEY: "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"
  BREVO_SENDER_EMAIL: "srshare2inspire@gmail.com"
  BREVO_SENDER_NAME: "Share2Inspire"
  
  # Configurações Ifthenpay
  IFTHENPAY_GATEWAY_KEY: "3532-9893-7426-5310"
  IFTHENPAY_CALLBACK_KEY: "SUbOv6HYq8WVAmSEqkLKZvjAhBPsr1LI9ifRXTtrvMs="
  IFTHENPAY_MBWAY_KEY: "UWP-547025"
  IFTHENPAY_PAYSHOP_KEY: "QTU-066969"
  IFTHENPAY_MULTIBANCO_KEY: "BXG-350883"
  
  # Chave secreta Flask
  FLASK_SECRET_KEY: "6BgB0lORveVCA/bsnK3XddCBnxvN3+Q8Z8We7cBeWAQ="

# Handlers simplificados
handlers:
- url: /.*
  script: auto
  secure: always

# Configurações de escalabilidade
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.6

# Configurações de recursos
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

