runtime: python311

# Entrypoint corrigido
entrypoint: gunicorn -b :$PORT main:app

# Variáveis de ambiente
env_variables:
  FLASK_APP: main.py
  FLASK_ENV: production
  FLASK_DEBUG: "False"
  GOOGLE_CLOUD_PROJECT: "share2inspire-beckend"
  
  # Gemini AI API Key
  GEMINI_API_KEY: "AIzaSyARqwQ8vIH8bha6hlZSpU1frY7IAR1oZhI"
  
  # Configurações de email (Brevo)
  # BREVO_API_KEY removido para usar Secret Manager
  BREVO_SENDER_EMAIL: "srshare2inspire@gmail.com"
  BREVO_SENDER_NAME: "Share2Inspire"
  
  # Configurações Ifthenpay (Segredos movidos para Secret Manager)
  
  # Chave secreta Flask (Movido para Secret Manager)

# Handlers simplificados
handlers:
- url: /.*
  script: auto
  secure: always

# Configurações de escalabilidade
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.6

# Configurações de recursos
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

